#include <ansi.h>

mapping *quest = ({
	([
		"id":          "wo kou",
		"name":        "ÙÁ¿Ü",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/quanzhou/npc/wokou.c",
	]),
	([
		"id":          "wang furen",
		"name":        "Íõ·òÈË",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/fuzhou/npc/wang.c",
	]),
	([
		"id":          "pu ren",
		"name":        "ÆÍÈË",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/emei/npc/puren.c",
	]),
	([
		"id":          "zu zhang",
		"name":        "×å³¤",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/zuzhang.c",
	]),
	([
		"id":          "zhao min",
		"name":        "ÕÔÃô",
		"type":        "É±",
		"bonus":       83,
		"msg":        "",
		"object":      "/d/tulong/yitian/npc/zhaomin2.c",
	]),
	([
		"id":          "zhao min",
		"name":        "ÕÔÃô",
		"type":        "É±",
		"bonus":       86,
		"msg":        "",
		"object":      "/d/tulong/yitian/npc/zhao.c",
	]),
	([
		"id":          "jiang baisheng",
		"name":        "½­°ÙÊ¤",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/taishan/npc/jiang.c",
	]),
	([
		"id":          "lao fuzi",
		"name":        "ÀÏ·ò×Ó",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/suzhou/npc/jiaoxi.c",
	]),
	([
		"id":          "yafu",
		"name":        "ÑÆ¸¾",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/hengshan/npc/yafu.c",
	]),
	([
		"id":          "shi tong",
		"name":        "ÊÌÍ¯",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/taohua/npc/shitong.c",
	]),
	([
		"id":          "tianbai daoren",
		"name":        "Ìì°ØµÀÈË",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/tianbai.c",
	]),
	([
		"id":          "meng jianxiong",
		"name":        "ÃÏ½¡ÐÛ",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/meng.c",
	]),
	([
		"id":          "ha dani",
		"name":        "¹þ´ïÄá",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guanwai/npc/hadani.c",
	]),
	([
		"id":          "lin zhennan",
		"name":        "ÁÖÕðÄÏ",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/fuzhou/npc/linzhennan.c",
	]),
	([
		"id":          "jianchu daoren",
		"name":        "½¨³ýµÀÈË",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/jianchu.c",
	]),
	([
		"id":          "zhangli",
		"name":        "ÕÆÀíµÀ³¤",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/quanzhen/npc/zhangli.c",
	]),
	([
		"id":          "jia ding",
		"name":        "¼Ò¶¡",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/guiyun/npc/jiading.c",
	]),
	([
		"id":          "fan yifei",
		"name":        "·¶Ò»·É",
		"type":        "É±",
		"bonus":       86,
		"msg":        "",
		"object":      "/d/guiyun/npc/fanyifei.c",
	]),
	([
		"id":          "menggu bing",
		"name":        "ÃÉ¹Å±ø",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/xiangyang/npc/menggubing.c",
	]),
	([
		"id":          "cheng chaofeng",
		"name":        "³Ì³°·ç",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/mingjiao/npc/chengchaofeng.c",
	]),
	([
		"id":          "lu dayou",
		"name":        "Â½´óÓÐ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/huashan/npc/dayou.c",
	]),
	([
		"id":          "zuo jiang",
		"name":        "×ô½«",
		"type":        "É±",
		"bonus":       92,
		"msg":        "",
		"object":      "/d/xiangyang/npc/zuo.c",
	]),
	([
		"id":          "ya jiang",
		"name":        "ÑÀ½«",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/xiangyang/npc/ya.c",
	]),
	([
		"id":          "ya pu",
		"name":        "ÑÆÆÍ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/taohua/npc/yapu.c",
	]),
	([
		"id":          "tianyi daoren",
		"name":        "ÌìÒÒµÀÈË",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/tianyi.c",
	]),
	([
		"id":          "tiansong daoren",
		"name":        "ÌìËÉµÀÈË",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/tiansong.c",
	]),
	([
		"id":          "zhen youqing",
		"name":        "ÕçÓÐÇì",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/suzhou/npc/shiye.c",
	]),
	([
		"id":          "an jiangang",
		"name":        "°²½¡¸Õ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/an.c",
	]),
	([
		"id":          "jin bing",
		"name":        "´ó½ð±ø",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/guiyun/npc/jinbing.c",
	]),
	([
		"id":          "feng liang",
		"name":        "·çÁ¼",
		"type":        "É±",
		"bonus":       81,
		"msg":        "",
		"object":      "/d/guiyun/npc/fengliang.c",
	]),
	([
		"id":          "maimaiti",
		"name":        "ÂòÂôÌá",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/xingxiu/npc/maimaiti.c",
	]),
	([
		"id":          "tuo lei",
		"name":        "ÍÏÀ×",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/xiangyang/npc/tuolei.c",
	]),
	([
		"id":          "pi jiang",
		"name":        "ñÔ½«",
		"type":        "É±",
		"bonus":       76,
		"msg":        "",
		"object":      "/d/xiangyang/npc/pi.c",
	]),
	([
		"id":          "wei shi",
		"name":        "ÇàÒÂÎäÊ¿",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/wei-shi3.c",
	]),
	([
		"id":          "yun sumei",
		"name":        "ÔÆËØÃ·",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/shenlong/npc/yunsumei.c",
	]),
	([
		"id":          "wu shi",
		"name":        "Ò»Æ·ÌÃÎäÊ¿",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/lingzhou/npc/yipinwushi.c",
	]),
	([
		"id":          "wu shi",
		"name":        "Ê¯ÈËÎäÊ¿",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/lingzhou/npc/shiwushi.c",
	]),
	([
		"id":          "yi lin",
		"name":        "ÒÇÁÕ",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/henshan/npc/yilin.c",
	]),
	([
		"id":          "feng yiming",
		"name":        "·ïÒ»Ãù",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/foshan/npc/fengyiming.c",
	]),
	([
		"id":          "gaoli shang",
		"name":        "¸ßÀöÉÌ",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/xiangyang/npc/gaoli.c",
	]),
	([
		"id":          "sun baopi",
		"name":        "Ëï°þÆ¤",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/suzhou/npc/sun.c",
	]),
	([
		"id":          "feng zhengdong",
		"name":        "·ëÕý¶«",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/suzhou/npc/feng.c",
	]),
	([
		"id":          "hongmao gui",
		"name":        "ºìÃ«¹í",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/quanzhou/npc/hongmao.c",
	]),
	([
		"id":          "zhangyao",
		"name":        "ÕÆÒ©µÀ³¤",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/quanzhen/npc/zhangyao.c",
	]),
	([
		"id":          "xiao wei",
		"name":        "Ð£Î¾",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/lingzhou/npc/xiaowei.c",
	]),
	([
		"id":          "gao genming",
		"name":        "¸ß¸ùÃ÷",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/huashan/npc/gao-genming.c",
	]),
	([
		"id":          "xianghuo daoren",
		"name":        "Ïã»ðµÀÈË",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/hangzhou/npc/xianghuo.c",
	]),
	([
		"id":          "zhong wanchou",
		"name":        "ÖÓÍò³ð",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/wanjiegu/npc/zhong.c",
	]),
	([
		"id":          "feng",
		"name":        "·ëÌú½³",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/village/npc/smith.c",
	]),
	([
		"id":          "zhou yi",
		"name":        "ÖÜç²",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/zhouyi.c",
	]),
	([
		"id":          "lu zhengping",
		"name":        "ÂÀÕýÆ½",
		"type":        "É±",
		"bonus":       83,
		"msg":        "",
		"object":      "/d/guiyun/npc/luzhengping.c",
	]),
	([
		"id":          "gao san",
		"name":        "¸ßÈýÄï×Ó",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/guiyun/npc/gaosan.c",
	]),
	([
		"id":          "guo fu",
		"name":        "¹ùÜ½",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/xiangyang/npc/guofu.c",
	]),
	([
		"id":          "gan baobao",
		"name":        "¸Ê±¦±¦",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/wanjiegu/npc/gan.c",
	]),
	([
		"id":          "pu ren",
		"name":        "ÆÍÈË",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/taohua/npc/puren.c",
	]),
	([
		"id":          "zhao min",
		"name":        "ÕÔÃô",
		"type":        "É±",
		"bonus":       83,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/zhaomin.c",
	]),
	([
		"id":          "liang fa",
		"name":        "Áº·¢",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/huashan/npc/liang-fa.c",
	]),
	([
		"id":          "lao xiucai",
		"name":        "ÀÏÐã²Å",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/huanghe/npc/xiucai.c",
	]),
	([
		"id":          "tuoba",
		"name":        "ÍØ°Ï",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/mingjiao/npc/tuoba.c",
	]),
	([
		"id":          "gao shanwang",
		"name":        "¸ßÉ½Íõ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/mingjiao/npc/gaoshanwang.c",
	]),
	([
		"id":          "feng gongying",
		"name":        "·â¹­Ó°",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/mingjiao/npc/fenggongying.c",
	]),
	([
		"id":          "shi daizi",
		"name":        "Ê©´÷×Ó",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/huashan/npc/shi-daizi.c",
	]),
	([
		"id":          "ji qingxu",
		"name":        "¼§ÇåÐé",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/kungfu/class/quanzhen/ji.c",
	]),
	([
		"id":          "xiao zhao",
		"name":        "Ð¡ÕÑ",
		"type":        "É±",
		"bonus":       82,
		"msg":        "",
		"object":      "/kungfu/class/mingjiao/xiaozhao.c",
	]),
	([
		"id":          "wei shi",
		"name":        "½õÒÂÎÀÊ¿",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/weishi2.c",
	]),
	([
		"id":          "daizu shouling",
		"name":        "´ö×åÊ×Áì",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/dali/npc/shouling.c",
	]),
	([
		"id":          "po yi",
		"name":        "ÆÆÒÉ",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/dali/npc/poyi.c",
	]),
	([
		"id":          "po chen",
		"name":        "ÆÆàÁ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/dali/npc/pochen.c",
	]),
	([
		"id":          "lao jisi",
		"name":        "ÀÏ¼ÀË¾",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/jisi1.c",
	]),
	([
		"id":          "ji si",
		"name":        "¼ÀË¾",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/dali/npc/jisi.c",
	]),
	([
		"id":          "jianghu yiren",
		"name":        "½­ºþÒÕÈË",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/jianghuyiren.c",
	]),
	([
		"id":          "duan wuwei",
		"name":        "¶ÎÎÞÎ·",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/duanwuwei.c",
	]),
	([
		"id":          "wu tiande",
		"name":        "ÎâÌìµÂ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/wutiande.c",
	]),
	([
		"id":          "tang huai",
		"name":        "ÌÆ»±",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/tanghuai.c",
	]),
	([
		"id":          "tang",
		"name":        "ÌÆÕÆ¹ñ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/tanghua.c",
	]),
	([
		"id":          "cheng yuhuan",
		"name":        "³ÌÓñ»·",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/yuhuan.c",
	]),
	([
		"id":          "xian laoban",
		"name":        "ÙþÀÏ°å",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/xian.c",
	]),
	([
		"id":          "wei chunfang",
		"name":        "Î¤´º·¼",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/city/npc/wei.c",
	]),
	([
		"id":          "tan youji",
		"name":        "Ì·ÓÑ¼Í",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/city/npc/shiye.c",
	]),
	([
		"id":          "qian yankai",
		"name":        "Ç®ÑÛ¿ª",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/qian.c",
	]),
	([
		"id":          "mao shiba",
		"name":        "Ã©Ê®°Ë",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/city/npc/mao18.c",
	]),
	([
		"id":          "gui gong",
		"name":        "¹ê¹«",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/city/npc/guigong.c",
	]),
	([
		"id":          "cheng yaofa",
		"name":        "³ÌÒ©·¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/city/npc/cheng.c",
	]),
	([
		"id":          "liang xinglu",
		"name":        "ÁºÐËÂ»",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/zhifu.c",
	]),
	([
		"id":          "yang laoban",
		"name":        "ÑîÀÏ°å",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/yang-laoban.c",
	]),
	([
		"id":          "li boyuan",
		"name":        "Àî²©Ô¨",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/xueshi.c",
	]),
	([
		"id":          "xiang ke",
		"name":        "Ïã¿Í",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/changan/npc/xiangke.c",
	]),
	([
		"id":          "tie gongji",
		"name":        "Ìú¹«¼¦",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/tiegongji.c",
	]),
	([
		"id":          "tang",
		"name":        "ÌË×ÓÊÖ",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/tang.c",
	]),
	([
		"id":          "shu chi",
		"name":        "Êé³Õ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/shuchi.c",
	]),
	([
		"id":          "chen jisheng",
		"name":        "³Â¼ÌÊ¢",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/shiye.c",
	]),
	([
		"id":          "monk",
		"name":        "Öª¿ÍºÍÉÐ",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/changan/npc/monk.c",
	]),
	([
		"id":          "liu laoshi",
		"name":        "ÁõÀÏÊµ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/liu.c",
	]),
	([
		"id":          "jin fuhuan",
		"name":        "½ð¸´»¹",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/jinfuhuan.c",
	]),
	([
		"id":          "shuang er",
		"name":        "Ë«¶ù",
		"type":        "É±",
		"bonus":       86,
		"msg":        "",
		"object":      "/d/beijing/npc/shuanger.c",
	]),
	([
		"id":          "qi biaoqing",
		"name":        "Æî±ëÇå",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/qibiaoqing.c",
	]),
	([
		"id":          "qian laoben",
		"name":        "Ç®ÀÏ±¾",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/qianlaoben.c",
	]),
	([
		"id":          "li lishi",
		"name":        "ÀîÁ¦ÊÀ",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/beijing/npc/lilishi.c",
	]),
	([
		"id":          "kang qinwang",
		"name":        "¿µÇ×Íõ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/kangqinwang.c",
	]),
	([
		"id":          "guan anji",
		"name":        "¹Ø°²»ù",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/guananji.c",
	]),
	([
		"id":          "fan gang",
		"name":        "·®¸Ù",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/fangang.c",
	]),
	([
		"id":          "feng asan",
		"name":        "·ë°¢Èý",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/kungfu/class/xiaoyao/fengas.c",
	]),
	([
		"id":          "qingxu daozhang",
		"name":        "ÇåÐéµÀ³¤",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/kungfu/class/wudang/qingxu.c",
	]),
	([
		"id":          "huizhen zunzhe",
		"name":        "»ÛÕæ×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-zhen.c",
	]),
	([
		"id":          "huixu zunzhe",
		"name":        "»ÛÐé×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-xu.c",
	]),
	([
		"id":          "huixiu zunzhe",
		"name":        "»ÛÐÞ×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-xiu.c",
	]),
	([
		"id":          "huise zunzhe",
		"name":        "»ÛÉ«×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-se.c",
	]),
	([
		"id":          "huiru zunzhe",
		"name":        "»ÛÈç×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-ru.c",
	]),
	([
		"id":          "huiming zunzhe",
		"name":        "»ÛÃû×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-ming.c",
	]),
	([
		"id":          "huikong zunzhe",
		"name":        "»Û¿Õ×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-kong.c",
	]),
	([
		"id":          "huijie zunzhe",
		"name":        "»Û½à×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-jie.c",
	]),
	([
		"id":          "huihe zunzhe",
		"name":        "»ÛºÏ×ðÕß",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/hui-he.c",
	]),
	([
		"id":          "mo bushou",
		"name":        "Äª²»ÊÕ",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/kungfu/class/gaibang/mo-bu.c",
	]),
	([
		"id":          "su mengqing",
		"name":        "ËÕÃÎÇå",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/kungfu/class/emei/su.c",
	]),
	([
		"id":          "li mingxia",
		"name":        "ÀîÃ÷Ï¼",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/kungfu/class/emei/li.c",
	]),
	([
		"id":          "fang bilin",
		"name":        "·½±ÌÁÕ",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/kungfu/class/emei/fang.c",
	]),
});
mapping query_questkh()
{
        return quest[random(sizeof(quest))];
}
