/d/city/npc/shanzi/shan-book
/d/city/npc/shanzi/yumao-shan
/d/city/npc/shanzi/tuan-shan
/d/city/npc/shanzi/zhe-shan
/d/city/npc/shanzi/yuban-shan
/d/city/npc/shanzi/chouwu-shan
/d/city/npc/shanzi/bajiao-shan
/d/city/npc/shanzi/tanxiang-shan
/d/city/npc/obj/peanut
/d/city/npc/obj/tofu
/clone/cloth/cuttonp
/d/city/npc/obj/beixin
/d/city/npc/obj/toukui
/d/city/npc/obj/cycle
/d/city/npc/obj/surcoat
/d/city/npc/obj/shield
/d/city/npc/obj/huwan
/d/city/npc/obj/zhitao
/d/city/npc/obj/huyao
/d/city/npc/obj/caoxie
/d/city/npc/obj/pixue
/d/city/npc/obj/shoutao
/d/city/npc/obj/tieshou
/d/city/npc/obj/jinsijia
/d/xingxiu/obj/fire
/d/item/obj/chanhs
/clone/misc/wood
/clone/misc/shoeshine
/clone/misc/brush
/clone/book/lbook0
/clone/book/lbook1
/clone/book/lbook2
/clone/book/lbook3
/clone/misc/jinchuang
/clone/misc/yangjing
/clone/misc/dust
/clone/misc/fashao
/clone/misc/shanghan
/clone/misc/xiaoshu
/clone/misc/dongshang
/clone/misc/zhike
/d/shenlong/obj/xionghuang
/clone/weapon/changjian
/clone/weapon/hammer
/clone/weapon/tudao
/clone/weapon/dagger
/clone/weapon/tiegun
/clone/weapon/gangdao
/clone/cloth/tiejia
/d/item/obj/jingtie
/clone/weapon/arrow
/clone/weapon/wolfarrow
/clone/weapon/bow
/clone/weapon/longbow
/d/city/npc/cloth/belt
/d/city/npc/cloth/boots
/d/city/npc/cloth/bu-shoes
/d/city/npc/cloth/color-dress
/d/city/npc/loth/fu-cloth
/d/city/npc/cloth/gui-dress
/d/city/npc/cloth/hat
/d/city/npc/cloth/jade-belt
/d/city/npc/cloth/liu-dress
/d/city/npc/cloth/marry-dress
/d/city/npc/cloth/mini-dress
/d/city/npc/cloth/moon-dress
/d/city/npc/cloth/pink-dress
/d/city/npc/cloth/qi-dress
/d/city/npc/cloth/red-dress
/d/city/npc/cloth/scarf
/d/city/npc/cloth/sha-dress
/d/city/npc/cloth/shoes
/d/city/npc/cloth/xian-cloth
/d/city/npc/cloth/xiu-cloth
/d/city/npc/cloth/xiu-scarf
/d/city/npc/cloth/yan-dress
/d/city/npc/cloth/zi-dress
/d/shaolin/obj/hulu
/d/city/obj/zhubang
/d/village/obj/zhujian
/d/xingxiu/obj/fire
/d/hangzhou/npc/obj/pork
/d/hangzhou/npc/obj/fish
/d/hangzhou/npc/obj/baozi
/d/hangzhou/npc/obj/shrimp
/d/hangzhou/npc/obj/chicken
/d/hangzhou/npc/obj/geng
/clone/tattoo/face1
/clone/tattoo/face2
/clone/tattoo/face3
/clone/tattoo/face4
/clone/tattoo/face5
/clone/tattoo/face6
/clone/tattoo/face7
/clone/tattoo/face8
/clone/tattoo/face9
/clone/tattoo/face10
/clone/tattoo/face11
/clone/tattoo/face12
/clone/tattoo/face13
/clone/tattoo/face14
/clone/tattoo/face15
/clone/tattoo/face16
/clone/tattoo/face17
/clone/tattoo/face18
/clone/tattoo/face19
/clone/tattoo/face20
/d/fuzhou/obj/xiuhua
/d/fuzhou/obj/flower_shoe
/d/fuzhou/obj/pink_cloth
/d/city/obj/goldring
/d/city/obj/necklace
/clone/misc/bicanfeng
/d/city3/npc/obj/feihuangshi
/d/city3/npc/obj/flower-leaf
/d/city3/npc/obj/tea-leaf
/d/city3/npc/obj/tielianzi
/d/beijing/obj/tanghulu
/d/beijing/obj/yao1
/d/beijing/obj/yao2
/d/beijing/obj/tea1
/d/beijing/obj/tea2
/d/beijing/obj/tea3
/d/beijing/obj/tea4
/d/city/obj/hdjiudai
/d/beijing/obj/kaoya
/d/beijing/obj/luobo
/d/beijing/obj/huluobo
/d/beijing/obj/baicai
/d/beijing/obj/dacong
/d/beijing/obj/tudou
/clone/weapon/tudao
/clone/weapon/dagger
/clone/weapon/wandao
/clone/weapon/gangdao
/d/changan/npc/obj/zi-luolan
/d/changan/npc/obj/hong-meigui
/d/changan/npc/obj/huang-meigui
/d/changan/npc/obj/lan-tiane
/d/changan/npc/obj/bai-chahua
/d/changan/npc/obj/hei-mudan
/d/changan/npc/obj/bao1
/d/changan/npc/obj/bao2
/d/changan/npc/obj/bao3
/clone/misc/diaogan
/clone/misc/yanwu
/clone/misc/shexiang
/d/wudu/obj/jiedudan
/d/changan/npc/obj/zuixunfeng 
/d/changan/npc/obj/snxiangji 
/d/changan/npc/obj/lhjiyu 
/d/changan/npc/obj/ring
/d/changan/npc/obj/wrists
/d/changan/npc/obj/neck 
/d/changan/npc/obj/yinjie 
/d/changan/npc/obj/zuanjie 
/d/changan/npc/obj/baojie 
/d/changan/npc/obj/jinjie
/d/changan/npc/obj/baijie
/d/changan/npc/obj/pingguo 
/d/changan/npc/obj/hamigua 
/d/changan/npc/obj/juzi
/d/changan/npc/obj/book_blade
/d/changan/npc/obj/book_unarmed  
/d/kaifeng/npc/obj/ciwan
/d/kaifeng/npc/obj/luowenhai
/d/kaifeng/npc/obj/bibohu
/d/luoyang/npc/obj/taoci 
/d/luoyang/npc/obj/taoci2 
/d/luoyang/npc/obj/taoci3 
/d/luoyang/npc/obj/taoci4 
/d/luoyang/npc/obj/taoci5 
/d/luoyang/npc/obj/taoci6 
/d/luoyang/npc/obj/taoci7 
/d/luoyang/npc/obj/taoci8
