#include <ansi.h>

mapping *quest = ({
	([
		"id":          "zhao yishang",
		"name":        "ÕÔÒ»ÉË",
		"type":        "É±",
		"bonus":       71,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/zhao1.c",
	]),
	([
		"id":          "sun sanhui",
		"name":        "ËïÈý»Ù",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/sun3.c",
	]),
	([
		"id":          "li sicui",
		"name":        "ÀîËÄ´Ý",
		"type":        "É±",
		"bonus":       70,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/li4.c",
	]),
	([
		"id":          "zhang san",
		"name":        "ÕÅÈý",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/wudang/npc/baibian.c",
	]),
	([
		"id":          "jiang baisheng",
		"name":        "½­°ÙÊ¤",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/taishan/npc/jiang.c",
	]),
	([
		"id":          "yafu",
		"name":        "ÑÆ¸¾",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/hengshan/npc/yafu.c",
	]),
	([
		"id":          "little monkey",
		"name":        "Ð¡ºï",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/huashan/npc/little_monkey.c",
	]),
	([
		"id":          "ha dani",
		"name":        "¹þ´ïÄá",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guanwai/npc/hadani.c",
	]),
	([
		"id":          "dongbei hu",
		"name":        "¶«±±»¢",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/guanwai/npc/dongbeihu.c",
	]),
	([
		"id":          "diao",
		"name":        "[1;33m½ðµñ[2;37;0m",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guanwai/npc/diao.c",
	]),
	([
		"id":          "hei xiong",
		"name":        "[36mºÚÐÜ[2;37;0m",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/guanwai/npc/bear.c",
	]),
	([
		"id":          "huanan hu",
		"name":        "»ªÄÏ»¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/fuzhou/npc/huananhu.c",
	]),
	([
		"id":          "wu liupo",
		"name":        "ÎâÁùÆÆ",
		"type":        "É±",
		"bonus":       90,
		"msg":        "",
		"object":      "/d/tulong/yitian/npc/wu6.c",
	]),
	([
		"id":          "heiyi ren",
		"name":        "ºÚÒÂÈË",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/heimuya/npc/heiyiren.c",
	]),
	([
		"id":          "young girl",
		"name":        "ÄêÇáÅ®µÜ×Ó",
		"type":        "É±",
		"bonus":       59,
		"msg":        "",
		"object":      "/d/shenlong/npc/girl.c",
	]),
	([
		"id":          "yu renyan",
		"name":        "ÓàÈËÑå",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/qingcheng/npc/yuyan.c",
	]),
	([
		"id":          "jia renda",
		"name":        "¼ÖÈË´ï",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/qingcheng/npc/jia.c",
	]),
	([
		"id":          "wu liupo",
		"name":        "ÎâÁùÆÆ",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/wu6.c",
	]),
	([
		"id":          "laohu",
		"name":        "ÀÏ»¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/wudang/npc/laohu.c",
	]),
	([
		"id":          "zhen youqing",
		"name":        "ÕçÓÐÇì",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/suzhou/npc/shiye.c",
	]),
	([
		"id":          "zhang laosan",
		"name":        "ÕÂÀÏÈý",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/shenlong/npc/zhang3.c",
	]),
	([
		"id":          "mu jianping",
		"name":        "ãå½£ÆÁ",
		"type":        "É±",
		"bonus":       59,
		"msg":        "",
		"object":      "/d/shenlong/npc/mujianping.c",
	]),
	([
		"id":          "horse",
		"name":        "[1;36mÇàæõÂí[2;37;0m",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/obj/horse.c",
	]),
	([
		"id":          "wanyan honglie",
		"name":        "ÍêÑÕºéÁÒ",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guiyun/npc/wanyanhonglie.c",
	]),
	([
		"id":          "qiu qianzhang",
		"name":        "ôÃÇ§ÕÉ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/guiyun/npc/qiuqianzhang.c",
	]),
	([
		"id":          "wei shi",
		"name":        "ÇàÒÂÎäÊ¿",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/taishan/npc/wei-shi3.c",
	]),
	([
		"id":          "shen renjun",
		"name":        "ÉêÈË¿¡",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/d/qingcheng/npc/shen.c",
	]),
	([
		"id":          "yan ji",
		"name":        "ÑÖ»ù",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guanwai/npc/yanji.c",
	]),
	([
		"id":          "wolf",
		"name":        "[37mÒ°ÀÇ[2;37;0m",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/guanwai/npc/wolf.c",
	]),
	([
		"id":          "feng yiming",
		"name":        "·ïÒ»Ãù",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/foshan/npc/fengyiming.c",
	]),
	([
		"id":          "cow",
		"name":        "[1;37m´ó»ÆÅ£[2;37;0m",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/wudang/npc/cow.c",
	]),
	([
		"id":          "qian erbai",
		"name":        "Ç®¶þ°Ü",
		"type":        "É±",
		"bonus":       83,
		"msg":        "",
		"object":      "/d/tulong/yitian/npc/qian2.c",
	]),
	([
		"id":          "sun baopi",
		"name":        "Ëï°þÆ¤",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/suzhou/npc/sun.c",
	]),
	([
		"id":          "gongzi",
		"name":        "¹«×Ó¸ç",
		"type":        "É±",
		"bonus":       66,
		"msg":        "",
		"object":      "/d/suzhou/npc/gongzi.c",
	]),
	([
		"id":          "feng zhengdong",
		"name":        "·ëÕý¶«",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/suzhou/npc/feng.c",
	]),
	([
		"id":          "fang yi",
		"name":        "·½âù",
		"type":        "É±",
		"bonus":       62,
		"msg":        "",
		"object":      "/d/shenlong/npc/fangyi.c",
	]),
	([
		"id":          "young boy",
		"name":        "ÄêÇáµÜ×Ó",
		"type":        "É±",
		"bonus":       58,
		"msg":        "",
		"object":      "/d/shenlong/npc/boy4.c",
	]),
	([
		"id":          "ba yi",
		"name":        "°ÍÒÀ",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/xingxiu/npc/bayi.c",
	]),
	([
		"id":          "old man",
		"name":        "ÀÏÕß",
		"type":        "É±",
		"bonus":       81,
		"msg":        "",
		"object":      "/d/shenlong/npc/old.c",
	]),
	([
		"id":          "fang renzhi",
		"name":        "·½ÈËÖÇ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/qingcheng/npc/fang.c",
	]),
	([
		"id":          "zheng qimie",
		"name":        "Ö£ÆßÃð",
		"type":        "É±",
		"bonus":       69,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/zheng7.c",
	]),
	([
		"id":          "wang bashuai",
		"name":        "Íõ°ËË¥",
		"type":        "É±",
		"bonus":       69,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/wang8.c",
	]),
	([
		"id":          "laohu",
		"name":        "ÀÏ»¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/hangzhou/npc/laohu.c",
	]),
	([
		"id":          "zhong wanchou",
		"name":        "ÖÓÍò³ð",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/wanjiegu/npc/zhong.c",
	]),
	([
		"id":          "zhou wushu",
		"name":        "ÖÜÎåÊä",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/zhou5.c",
	]),
	([
		"id":          "yang lianting",
		"name":        "ÑîÁ«Í¤",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/heimuya/npc/yang.c",
	]),
	([
		"id":          "mao niu",
		"name":        "êóÅ£",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/xueshan/npc/maoniu.c",
	]),
	([
		"id":          "guo fu",
		"name":        "¹ùÜ½",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/xiangyang/npc/guofu.c",
	]),
	([
		"id":          "gan baobao",
		"name":        "¸Ê±¦±¦",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/wanjiegu/npc/gan.c",
	]),
	([
		"id":          "wan daping",
		"name":        "Íò´óÆ½",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/songshan/npc/wan.c",
	]),
	([
		"id":          "qian erbai",
		"name":        "Ç®¶þ°Ü",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/mingjiao/yuan/qian2.c",
	]),
	([
		"id":          "ma zei",
		"name":        "ÂíÔô",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/huanghe/npc/mazei.c",
	]),
	([
		"id":          "ouyang ke",
		"name":        "Å·Ñô¿Ë",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/xingxiu/npc/ke.c",
	]),
	([
		"id":          "caihua zi",
		"name":        "²É»¨×Ó",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/xingxiu/npc/caihua.c",
	]),
	([
		"id":          "shi dengda",
		"name":        "Ê·µÇ´ï",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/songshan/npc/shi.c",
	]),
	([
		"id":          "young boy",
		"name":        "ÄêÇáµÜ×Ó",
		"type":        "É±",
		"bonus":       61,
		"msg":        "",
		"object":      "/d/shenlong/npc/boy3.c",
	]),
	([
		"id":          "young boy",
		"name":        "ÄêÇáµÜ×Ó",
		"type":        "É±",
		"bonus":       59,
		"msg":        "",
		"object":      "/d/shenlong/npc/boy.c",
	]),
	([
		"id":          "ji rentong",
		"name":        "¼ªÈËÍ¨",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/d/qingcheng/npc/ji.c",
	]),
	([
		"id":          "shan yang",
		"name":        "É½Ñò",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/dali/npc/shanyang.c",
	]),
	([
		"id":          "laohu",
		"name":        "ÀÏ»¢",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/dali/npc/laohu.c",
	]),
	([
		"id":          "jianghu yiren",
		"name":        "½­ºþÒÕÈË",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/dali/npc/jianghuyiren.c",
	]),
	([
		"id":          "he hongyao",
		"name":        "ºÎºìÒ©",
		"type":        "É±",
		"bonus":       96,
		"msg":        "",
		"object":      "/d/dali/npc/hehongyao.c",
	]),
	([
		"id":          "gongzi",
		"name":        "¹ó¹«×Ó",
		"type":        "É±",
		"bonus":       68,
		"msg":        "",
		"object":      "/d/dali/npc/guigongzi.c",
	]),
	([
		"id":          "shui niu",
		"name":        "Ë®Å£",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/dali/npc/cow.c",
	]),
	([
		"id":          "wu tiande",
		"name":        "ÎâÌìµÂ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/wutiande.c",
	]),
	([
		"id":          "tang huai",
		"name":        "ÌÆ»±",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/tanghuai.c",
	]),
	([
		"id":          "tang",
		"name":        "ÌÆÕÆ¹ñ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city3/npc/tanghua.c",
	]),
	([
		"id":          "tan youji",
		"name":        "Ì·ÓÑ¼Í",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/city/npc/shiye.c",
	]),
	([
		"id":          "shi song",
		"name":        "Ê·ËÉ",
		"type":        "É±",
		"bonus":       76,
		"msg":        "",
		"object":      "/d/city/npc/shisong.c",
	]),
	([
		"id":          "qian yankai",
		"name":        "Ç®ÑÛ¿ª",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/qian.c",
	]),
	([
		"id":          "huangbiaoma",
		"name":        "[1;33m»ÆæôÂí[2;37;0m",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/huangbiaoma.c",
	]),
	([
		"id":          "cui yuanwai",
		"name":        "´ÞÔ±Íâ",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/city/npc/cui.c",
	]),
	([
		"id":          "cheng yaofa",
		"name":        "³ÌÒ©·¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/city/npc/cheng.c",
	]),
	([
		"id":          "bailuotuo",
		"name":        "[1;37m°×ÂæÍÕ[2;37;0m",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/city/npc/camel.c",
	]),
	([
		"id":          "zhang san",
		"name":        "ÕÅÈý",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/city/npc/baibian.c",
	]),
	([
		"id":          "liang xinglu",
		"name":        "ÁºÐËÂ»",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/zhifu.c",
	]),
	([
		"id":          "li boyuan",
		"name":        "Àî²©Ô¨",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/xueshi.c",
	]),
	([
		"id":          "tie gongji",
		"name":        "Ìú¹«¼¦",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/tiegongji.c",
	]),
	([
		"id":          "tang",
		"name":        "ÌË×ÓÊÖ",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/tang.c",
	]),
	([
		"id":          "shu chi",
		"name":        "Êé³Õ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/changan/npc/shuchi.c",
	]),
	([
		"id":          "chen jisheng",
		"name":        "³Â¼ÌÊ¢",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/changan/npc/shiye.c",
	]),
	([
		"id":          "ling feixue",
		"name":        "Áè·ÉÑ©",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/d/changan/npc/lingfeixue.c",
	]),
	([
		"id":          "qian laoben",
		"name":        "Ç®ÀÏ±¾",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/qianlaoben.c",
	]),
	([
		"id":          "lama",
		"name":        "À®Âï",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/lama.c",
	]),
	([
		"id":          "feng jizhong",
		"name":        "·ç¼ÊÖÐ",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/beijing/npc/fengjizhong.c",
	]),
	([
		"id":          "qing",
		"name":        "Ð¡Çà",
		"type":        "É±",
		"bonus":       88,
		"msg":        "",
		"object":      "/d/baituo/npc/xiaoqing.c",
	]),
	([
		"id":          "trainer",
		"name":        "½ÌÁ·",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/baituo/npc/trainer.c",
	]),
	([
		"id":          "tiger",
		"name":        "ÀÏ»¢",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/baituo/npc/tiger.c",
	]),
	([
		"id":          "snaker",
		"name":        "ÎèÉßÈË",
		"type":        "É±",
		"bonus":       64,
		"msg":        "",
		"object":      "/d/baituo/npc/snaker.c",
	]),
	([
		"id":          "shanzei tou",
		"name":        "É½ÔôÍ·",
		"type":        "É±",
		"bonus":       65,
		"msg":        "",
		"object":      "/d/baituo/npc/shanzei3.c",
	]),
	([
		"id":          "playboy",
		"name":        "»¨»¨¹«×Ó",
		"type":        "É±",
		"bonus":       65,
		"msg":        "",
		"object":      "/d/baituo/npc/playboy.c",
	]),
	([
		"id":          "men wei",
		"name":        "ÃÅÎÀ",
		"type":        "É±",
		"bonus":       97,
		"msg":        "",
		"object":      "/d/baituo/npc/menwei.c",
	]),
	([
		"id":          "lion",
		"name":        "ÐÛÊ¨",
		"type":        "É±",
		"bonus":       72,
		"msg":        "",
		"object":      "/d/baituo/npc/lion.c",
	]),
	([
		"id":          "ge lunbu",
		"name":        "¸ðÂ×²¼",
		"type":        "É±",
		"bonus":       80,
		"msg":        "",
		"object":      "/kungfu/class/xueshan/gelunbu.c",
	]),
	([
		"id":          "mo bushou",
		"name":        "Äª²»ÊÕ",
		"type":        "É±",
		"bonus":       60,
		"msg":        "",
		"object":      "/kungfu/class/gaibang/mo-bu.c",
	]),
});
mapping query_questdg()
{
        return quest[random(sizeof(quest))];
}
