#include <ansi.h>

mapping *quest = ({
	([
		"id":          "zhang chengfeng",
		"name":        "’≈≥À∑Á",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhang1.c",
	]),
	([
		"id":          "yu canghai",
		"name":        "”‡≤◊∫£",
		"type":        "…±",
		"bonus":       66,
		"msg":        "",
		"object":      "/d/qingcheng/npc/hai.c",
	]),
	([
		"id":          "feng xifan",
		"name":        "∑ÎŒ˝∑∂",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/d/guanwai/npc/fengxifan.c",
	]),
	([
		"id":          "zhao banshan",
		"name":        "’‘∞Î…Ω",
		"type":        "…±",
		"bonus":       66,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/zhao.c",
	]),
	([
		"id":          "wuchen daozhang",
		"name":        "Œﬁ≥æµ¿≥§",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/hangzhou/honghua/wuchen.c",
	]),
	([
		"id":          "zhang chengyun",
		"name":        "’≈≥À‘∆",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhang2.c",
	]),
	([
		"id":          "zhao he",
		"name":        "’‘∫◊",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhaohe.c",
	]),
	([
		"id":          "fan song",
		"name":        "∑∂À…",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/d/heimuya/npc/fansong.c",
	]),
	([
		"id":          "cong buqi",
		"name":        "¥‘≤ª∆˙",
		"type":        "…±",
		"bonus":       73,
		"msg":        "",
		"object":      "/kungfu/class/huashan/cong-buqi.c",
	]),
	([
		"id":          "cheng buyou",
		"name":        "≥…≤ª”«",
		"type":        "…±",
		"bonus":       69,
		"msg":        "",
		"object":      "/kungfu/class/huashan/cheng-buyou.c",
	]),
	([
		"id":          "taoshi xian",
		"name":        "Ã“ µœ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao6.c",
	]),
	([
		"id":          "taohua xian",
		"name":        "Ã“ª®œ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao5.c",
	]),
	([
		"id":          "taoye xian",
		"name":        "Ã““∂œ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao4.c",
	]),
	([
		"id":          "taozhi xian",
		"name":        "Ã“÷¶œ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao3.c",
	]),
	([
		"id":          "taogan xian",
		"name":        "Ã“∏…œ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao2.c",
	]),
	([
		"id":          "taogen xian",
		"name":        "Ã“∏˘œ…",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/d/city/npc/tao1.c",
	]),
	([
		"id":          "qu lingfeng",
		"name":        "«˙¡È∑Á",
		"type":        "…±",
		"bonus":       89,
		"msg":        "",
		"object":      "/kungfu/class/taohua/qu.c",
	]),
	([
		"id":          "xu xueting",
		"name":        "–Ì—©Õ§",
		"type":        "…±",
		"bonus":       69,
		"msg":        "",
		"object":      "/kungfu/class/shenlong/xu.c",
	]),
	([
		"id":          "peng youjing",
		"name":        "≈Ì”–æ¥",
		"type":        "…±",
		"bonus":       69,
		"msg":        "",
		"object":      "/kungfu/class/gaibang/peng.c",
	]),
	([
		"id":          "liang zhanglao",
		"name":        "¡∫≥§¿œ",
		"type":        "…±",
		"bonus":       89,
		"msg":        "",
		"object":      "/kungfu/class/gaibang/liang.c",
	]),
	([
		"id":          "jian zhanglao",
		"name":        "ºÚ≥§¿œ",
		"type":        "…±",
		"bonus":       70,
		"msg":        "",
		"object":      "/kungfu/class/gaibang/jian.c",
	]),
	([
		"id":          "duan yu",
		"name":        "∂Œ”˛",
		"type":        "…±",
		"bonus":       106,
		"msg":        "",
		"object":      "/kungfu/class/duan/duanyu.c",
	]),
	([
		"id":          "xiang wentian",
		"name":        "œÚŒ ÃÏ",
		"type":        "…±",
		"bonus":       85,
		"msg":        "",
		"object":      "/d/heimuya/npc/xiang.c",
	]),
	([
		"id":          "guo jing",
		"name":        "π˘æ∏",
		"type":        "…±",
		"bonus":       81,
		"msg":        "",
		"object":      "/d/xiangyang/npc/guo.c",
	]),
	([
		"id":          "zhang chengfeng",
		"name":        "’≈≥À∑Á",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhang1.c",
	]),
	([
		"id":          "dongfang bubai",
		"name":        "∂´∑Ω≤ª∞‹",
		"type":        "…±",
		"bonus":       85,
		"msg":        "",
		"object":      "/d/heimuya/npc/dongfang.c",
	]),
	([
		"id":          "miao renfeng",
		"name":        "√Á»À∑Ô",
		"type":        "…±",
		"bonus":       82,
		"msg":        "",
		"object":      "/d/shaolin/npc/miao.c",
	]),
	([
		"id":          "ren woxing",
		"name":        "»ŒŒ“––",
		"type":        "…±",
		"bonus":       80,
		"msg":        "",
		"object":      "/d/heimuya/npc/renwoxing.c",
	]),
	([
		"id":          "zuo lengchan",
		"name":        "◊Û¿‰Ï¯",
		"type":        "…±",
		"bonus":       78,
		"msg":        "",
		"object":      "/d/songshan/npc/zuo.c",
	]),
	([
		"id":          "feng xifan",
		"name":        "∑ÎŒ˝∑∂",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/d/guanwai/npc/fengxifan.c",
	]),
	([
		"id":          "zhang chengyun",
		"name":        "’≈≥À‘∆",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhang2.c",
	]),
	([
		"id":          "zhao he",
		"name":        "’‘∫◊",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/d/heimuya/npc/zhaohe.c",
	]),
	([
		"id":          "yue nv",
		"name":        "‘Ω≈Æ",
		"type":        "…±",
		"bonus":       85,
		"msg":        "",
		"object":      "/d/hangzhou/npc/yuenv.c",
	]),
	([
		"id":          "fan song",
		"name":        "∑∂À…",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/d/heimuya/npc/fansong.c",
	]),
	([
		"id":          "murong fu",
		"name":        "ƒΩ»›∏¥",
		"type":        "…±",
		"bonus":       78,
		"msg":        "",
		"object":      "/kungfu/class/murong/murongfu.c",
	]),
	([
		"id":          "murong longcheng",
		"name":        "ƒΩ»›¡˙≥«",
		"type":        "…±",
		"bonus":       87,
		"msg":        "",
		"object":      "/kungfu/class/murong/longcheng.c",
	]),
	([
		"id":          "zhuo bufan",
		"name":        "◊ø≤ª∑≤",
		"type":        "…±",
		"bonus":       82,
		"msg":        "",
		"object":      "/kungfu/class/lingjiu/zhuo.c",
	]),
	([
		"id":          "hu yizhi",
		"name":        "∫˙“›÷Æ",
		"type":        "…±",
		"bonus":       77,
		"msg":        "",
		"object":      "/kungfu/class/hu/huyizhi.c",
	]),
	([
		"id":          "yang guo",
		"name":        "—Óπ˝",
		"type":        "…±",
		"bonus":       88,
		"msg":        "",
		"object":      "/kungfu/class/gumu/yang.c",
	]),
	([
		"id":          "jinlun fawang",
		"name":        "Ω¬÷∑®Õı",
		"type":        "…±",
		"bonus":       84,
		"msg":        "",
		"object":      "/kungfu/class/xueshan/fawang.c",
	]),
	([
		"id":          "hong antong",
		"name":        "∫È∞≤Õ®",
		"type":        "…±",
		"bonus":       82,
		"msg":        "",
		"object":      "/kungfu/class/shenlong/hong.c",
	]),
	([
		"id":          "du nan",
		"name":        "∂…ƒ—",
		"type":        "…±",
		"bonus":       85,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/du-nan.c",
	]),
	([
		"id":          "du jie",
		"name":        "∂…ΩŸ",
		"type":        "…±",
		"bonus":       83,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/du-jie.c",
	]),
	([
		"id":          "du e",
		"name":        "∂…∂Ú",
		"type":        "…±",
		"bonus":       84,
		"msg":        "",
		"object":      "/kungfu/class/shaolin/du-e.c",
	]),
	([
		"id":          "lin chaoying",
		"name":        "¡÷≥Ø”¢",
		"type":        "…±",
		"bonus":       87,
		"msg":        "",
		"object":      "/kungfu/class/gumu/lin.c",
	]),
	([
		"id":          "duan yu",
		"name":        "∂Œ”˛",
		"type":        "…±",
		"bonus":       75,
		"msg":        "",
		"object":      "/kungfu/class/duan/duanyu.c",
	]),
	([
		"id":          "duan yanqing",
		"name":        "∂Œ—”«Ï",
		"type":        "…±",
		"bonus":       78,
		"msg":        "",
		"object":      "/kungfu/class/duan/duanyq.c",
	]),
});
mapping query_questdg()
{
        return quest[random(sizeof(quest))];
}
