// Copyright (C) 2002-2004, by Lonely. All rights reserved.
// This software can not be used, copied, or modified 
// in any form without the written permission from authors.
// ap_power and dp_power be used in perform and the skill's
// valid_damage.

#define BAS                       2
#define COU                       20

mapping attack_lvl = ([
        "yinyang-shiertian"     : 10,
        "daojian-guizhen"       : 9,
        "never-defeated"        : 8,
        "jiuyin-shengong"       : 7,
        "bluesea-force"         : 7,
        "kuihua-mogong"         : 9,
        "sanfen-jianshu"        : 5,
        "huanyin-zhi"           : 5,
        "ningxue-shenzhao"      : 5,
        "zijinbagua-dao"        : 5,
        "taixuan-gong"          : 6,
        "mingyu-gong"           : 6,
        "pixie-jian"            : 7,
        "tie-zhang"             : 5,
        "jinshe-jian"           : 6,
        "xuanming-zhang"        : 5,
        "baihua-cuoquan"        : 6,
        "jiuyin-zhao"           : 6,
        "jinshe-zhang"          : 4,
        "jinshe-zhui"           : 3,
        "yuenv-jian"            : 5,
        "wuhu-duanmendao"       : 4,
        "bizhen-qingzhang"      : 5,
        "weituo-gun"            : 2,
        "cibei-dao"             : 2,
        "fengyun-shou"          : 2,
        "sanhua-zhang"          : 2,
        "shenzhang-bada"        : 2,
        "qianye-shou"           : 2,
        "xumishan-zhang"        : 3,
        "xiuluo-dao"            : 3,
        "wuchang-zhang"         : 4,
        "zui-gun"               : 4,
        "wuxiang-zhi"           : 3,
        "jingang-quan"          : 3,
        "fumo-jian"             : 4,
        "wuxiang-zhi"           : 5,
        "xiuluo-zhi"            : 3,
        "yingzhua-gong"         : 3,
        "nianhua-zhi"           : 5,
        "banruo-zhang"          : 4,
        "jingang-zhi"           : 3,
        "duoluoye-zhi"          : 4,
        "yizhi-chan"            : 4,
        "longzhua-gong"         : 5,
        "damo-jian"             : 6,
        "riyue-bian"            : 7,
        "taiji-jian"            : 6,
        "taiji-quan"            : 6,
        "xuanxu-dao"            : 4,
        "raozhi-roujian"        : 5,
        "shenmen-jian"          : 4,
        "yitian-zhang"          : 4,
        "huzhua-shou"           : 4,
        "zhenshan-zhang"        : 4,
        "dugu-jiujian"          : 7,
        "poyu-quan"             : 4,
        "hunyuan-zhang"         : 4,
        "fanliangyi-dao"        : 6,
        "kuangfeng-jian"        : 5,
        "yunv-sword"            : 5,
        "huashan-jianfa"        : 5,
        "huifeng-jian"          : 4,
        "piaoxue-zhang"         : 4,
        "yanxing-dao"           : 5,
        "tiangang-zhi"          : 4,
        "jinding-zhang"         : 4,
        "xiantian-gong"         : 7,
        "kongming-quan"         : 3,
        "chongyang-shenzhang"   : 4,
        "zhongnan-zhi"          : 3,
        "haotian-zhang"         : 4,
        "quanzhen-jian"         : 5,
        "yuxiao-jian"           : 6,
        "canglang-bian"         : 4,
        "lanhua-shou"           : 4,
        "xuanfeng-tui"          : 3,
        "tanzhi-shentong"       : 7,
        "luoying-shenjian"      : 5,
        "luoying-shenzhang"     : 4,
        "dragon-strike"         : 7,
        "dagou-bang"            : 6,
        "liuhe-dao"             : 3,
        "xiaoyaoyou"            : 4,
        "fengmo-zhang"          : 4,
        "shexing-diaoshou"      : 3,
        "fumo-zhang"            : 4,
        "suohou-gong"           : 3,
        "chansi-shou"           : 5,
        "jueming-tui"           : 3,
        "mantianhuayu"          : 4,
        "shenzhaojing"          : 5,
        "xuedao-daofa"          : 5,
        "liancheng-jianfa"      : 6,
        "mingwang-jian"         : 5,
        "yujiamu-quan"          : 4,
        "dashou-yin"            : 5,
        "longxiang-gong"        : 6,
        "riyue-lun"             : 5,
        "huoyan-dao"            : 5,
        "chousui-zhang"         : 3,
        "sanyin-zhua"           : 4,
        "chanhun-suo"           : 6,
        "feixing-shu"           : 2,
        "tianshan-zhang"        : 5,
        "sad-strike"            : 6,
        "xuantie-jian"          : 5,
        "yunv-jian"             : 5,
        "chilian-shenzhang"     : 4,
        "yinsuo-jinling"        : 3,
        "tianluo-diwang"        : 4,
        "meinv-quan"            : 4,
        "yufeng-zhen"           : 2,
        "zhemei-shou"           : 5,
        "liuyue-jian"           : 5,
        "ruyi-dao"              : 4,
        "qingyun-shou"          : 3,
        "liuyang-zhang"         : 6,
        "jiuyang-shengong"      : 7,
        "hujia-daofa"           : 6,
        "miaojia-jian"          : 6,
        "canhe-zhi"             : 6,
        "six-finger"            : 7,
        "yiyang-zhi"            : 5,
        "jinyu-quan"            : 3,
        "wuluo-zhang"           : 4,
        "tangmen-throwing"      : 6,
        "hamagong"              : 6,
]);

mapping parry_lvl = ([
        "yinyang-shiertian"     : 10,
        "daojian-guizhen"       : 9,
        "never-defeated"        : 8,
        "jiuyin-shengong"       : 7,
        "bluesea-force"         : 5,
        "sanfen-jianshu"        : 5,
        "huanyin-zhi"           : 3,
        "ningxue-shenzhao"      : 3,
        "zijinbagua-dao"        : 4,
        "taixuan-gong"          : 5,
        "douzhuan-xingyi"       : 8,
        "mingyu-gong"           : 4,
        "pixie-jian"            : 2,
        "jinshe-jian"           : 6,
        "baihua-cuoquan"        : 3,
        "jiuyin-zhao"           : 2,
        "yuenv-jian"            : 4,
        "wuhu-duanmendao"       : 3,
        "bizhen-qingzhang"      : 2,
        "weituo-gun"            : 2,
        "cibei-dao"             : 2,
        "pudu-zhang"            : 2,
        "qianye-shou"           : 2,
        "xiuluo-dao"            : 3,
        "wuchang-zhang"         : 2,
        "zui-gun"               : 2,
        "jingang-quan"          : 2,
        "fumo-jian"             : 3,
        "xiuluo-zhi"            : 2,
        "nianhua-zhi"           : 2,
        "banruo-zhang"          : 5,
        "jingang-zhi"           : 2,
        "duoluoye-zhi"          : 3,
        "damo-jian"             : 5,
        "riyue-bian"            : 5,
        "jingang-buhuaiti"      : 6,
        "taiji-jian"            : 7,
        "taiji-quan"            : 6,
        "xuanxu-dao"            : 3,
        "raozhi-roujian"        : 3,
        "shenmen-jian"          : 2,
        "huzhua-shou"           : 2,
        "dugu-jiujian"          : 8,
        "poyu-quan"             : 2,
        "fanliangyi-dao"        : 5,
        "kuangfeng-jian"        : 2,
        "yunv-sword"            : 4,
        "huashan-jianfa"        : 5,
        "huifeng-jian"          : 5,
        "piaoxue-zhang"         : 2,
        "yanxing-dao"           : 4,
        "tiangang-zhi"          : 2,
        "xiantian-gong"         : 4,
        "kongming-quan"         : 3,
        "zhongnan-zhi"          : 2,
        "quanzhen-jian"         : 5,
        "tanzhi-shentong"       : 5,
        "yuxiao-jian"           : 5,
        "canglang-bian"         : 4,
        "lanhua-shou"           : 3,
        "xuanfeng-tui"          : 2,
        "luoying-shenjian"      : 4,
        "luoying-shenzhang"     : 3,
        "dagou-bang"            : 6,
        "liuhe-dao"             : 4,
        "xiaoyaoyou"            : 2,
        "fengmo-zhang"          : 4,
        "shexing-diaoshou"      : 2,
        "fumo-zhang"            : 4,
        "suohou-gong"           : 2,
        "chansi-shou"           : 3,
        "shenzhaojing"          : 4,
        "xuedao-daofa"          : 5,
        "liancheng-jianfa"      : 6,
        "mingwang-jian"         : 4,
        "yujiamu-quan"          : 2,
        "dashou-yin"            : 2,
        "longxiang-gong"        : 3,
        "riyue-lun"             : 5,
        "huoyan-dao"            : 2,
        "jingang-chu"           : 6,
        "chousui-zhang"         : 2,
        "sanyin-zhua"           : 2,
        "chanhun-suo"           : 3,
        "tianshan-zhang"        : 5,
        "sad-strike"            : 3,
        "xuantie-jian"          : 4,
        "yunv-jian"             : 4,
        "yinsuo-jinling"        : 4,
        "tianluo-diwang"        : 2,
        "meinv-quan"            : 2,
        "zhemei-shou"           : 7,
        "liuyue-jian"           : 5,
        "ruyi-dao"              : 5,
        "qingyun-shou"          : 3,
        "liuyang-zhang"         : 2,
        "youming-guizhao"       : 6,
        "zhougong-jian"         : 4,
        "wuliang-jian"          : 4,
        "tianyu-qijian"         : 5,
        "qiankun-danuoyi"       : 9,
        "jiuyang-shengong"      : 3,
        "shenghuo-ling"         : 5,
        "pili-shou"             : 2,
        "liehuo-jian"           : 3,
        "huagu-mianzhang"       : 2,
        "shedao-qigong"         : 5,
        "hujia-daofa"           : 5,
        "baisheng-daofa"        : 3,
        "miaojia-jian"          : 5,
        "tianchang-zhang"       : 2,
        "hujia-quan"            : 2,
        "hamagong"              : 4,
        "baibian-daxue"         : 3,
        "lingshe-zhangfa"       : 5,
        "shentuo-zhang"         : 3,
        "canhe-zhi"             : 5,
        "longcheng-shendao"     : 6,
        "murong-daofa"          : 5,
        "murong-jianfa"         : 5,
        "qixing-quan"           : 2,
        "six-finger"            : 4,
        "yiyang-zhi"            : 5,
        "duanjia-jian"          : 3,
        "feifeng-bian"          : 6,
        "jinyu-quan"            : 2,
        "wuluo-zhang"           : 2,
        "wuzhan-mei"            : 5,
        "boyun-suowu"           : 2,
]);

mapping dodge_lvl = ([
        "yinyang-shiertian"     : 10,
        "never-defeated"        : 7,
        "jiuyin-shengong"       : 6,
        "bluesea-force"         : 5,
        "kuihua-mogong"         : 9,
        "taixuan-gong"          : 3,
        "mingyu-gong"           : 4,
        "pixie-jian"            : 8,
        "yunlong-shenfa"        : 2,
        "zhuangzi-wu"           : 3,
        "shaolin-shenfa"        : 2,
        "tiyunzong"             : 6,
        "feiyan-huixiang"       : 2,
        "zhutian-bu"            : 4,
        "jinyan-gong"           : 4,
        "luoying-shenfa"        : 4,
        "xiaoyaoyou"            : 3,
        "feiyan-zoubi"          : 4,
        "shenkong-xing"         : 4,
        "feixing-shu"           : 3,
        "zhaixing-gong"         : 4,
        "tianluo-diwang"        : 3,
        "yunv-shenfa"           : 4,
        "lingbo-weibu"          : 9,
        "yueying-wubu"          : 4,
        "qingfu-shenfa"         : 3,
        "yixing-bufa"           : 5,
        "sixiang-bufa"          : 4,
        "chanchu-bufa"          : 4,
        "douzhuan-xingyi"       : 8,
        "beidou-xianzong"       : 3,
        "tiannan-bufa"          : 3,
        "qiulin-shiye"          : 4,
        "shenxing-baibian"      : 2,
]);

mapping force_lvl = ([
        "yinyang-shiertian"     : 10, 
        "jiuyang-shengong"      : 8,
        "taixuan-gong"          : 7,
        "mingyu-gong"           : 7,
        "yijinjing"             : 7,
        "freezing-force"        : 6,
        "taiji-shengong"        : 6,
        "beiming-shengong"      : 5,
        "bahuang-gong"          : 5,
        "xiantian-gong"         : 5,
        "hamagong"              : 6,
        "pixie-jian"            : 4,
        "longxiang-gong"        : 5,
        "shenzhaojing"          : 5,
        "luohan-fumogong"       : 5,
        "huagong-dafa"          : 4,
        "xixing-dafa"           : 4,
        "zixia-shengong"        : 4,
        "shenyuan-gong"         : 4,
        "bibo-shengong"         : 4,
        "lengyue-shengong"      : 4,
        "kurong-changong"       : 4,
        "huntian-qigong"        : 4,
        "nuhai-kuangtao"        : 4,
        "linji-zhuang"          : 4,
        "sanku-shengong"        : 4,
        "xuanming-shengong"     : 4,
        "zhanshen-xinjing"      : 4,
        "shenghuo-shengong"     : 3,
        "xiaowuxiang"           : 3,
        "quanzhen-xinfa"        : 3,
        "zihui-xinfa"           : 3,
        "yunv-xinfa"            : 3,
        "shenlong-xinfa"        : 3,
        "hunyuan-yiqi"          : 3,
        "xuehai-mogong"         : 3,
        "yinyun-ziqi"           : 3,
        "biyun-xinfa"           : 3,
        "yijin-duangu"          : 2,
        "mizong-neigong"        : 2,
        "huashan-xinfa"         : 2,
        "emei-xinfa"            : 2,
        "shaolin-xinfa"         : 1,
        "guixi-gong"            : 1,
]);

mapping defend_lvl = ([
        "yinyang-shiertian"     : 10,
        "taixuan-gong"          : 5,
        "mingyu-gong"           : 5,
        "pixie-jian"            : 6,
        "jingang-buhuaiti"      : 6,
        "taiji-jian"            : 9,
        "taiji-quan"            : 8,
        "dugu-jiujian"          : 7,
        "lingbo-weibu"          : 9,
        "qiankun-danuoyi"       : 9,
        "jiuyang-shengong"      : 6,
        "hujia-daofa"           : 4,
        "douzhuan-xingyi"       : 8,
        "six-finger"            : 4,
        "xiantian-gong"         : 5,
        "yijinjing"             : 6,
        "daojian-guizhen"       : 5,
]);

mapping damage_lvl = ([
        "yinyang-shiertian"     : 10,
        "daojian-guizhen"       : 7,
        "never-defeated"        : 6,
        "jiuyin-shengong"       : 6,
        "bluesea-force"         : 6,
        "kuihua-mogong"         : 6,
        "sanfen-jianshu"        : 4,
        "huanyin-zhi"           : 5,
        "ningxue-shenzhao"      : 5,
        "zijinbagua-dao"        : 5,
        "taixuan-gong"          : 6,
        "mingyu-gong"           : 5,
        "pixie-jian"            : 7,
        "tie-zhang"             : 8,
        "jinshe-jian"           : 4,
        "xuanming-zhang"        : 7,
        "baihua-cuoquan"        : 5,
        "jiuyin-zhao"           : 7,
        "jinshe-zhang"          : 4,
        "jinshe-zhui"           : 4,
        "yuenv-jian"            : 4,
        "wuhu-duanmendao"       : 5,
        "bizhen-qingzhang"      : 6,
        "pudu-zhang"            : 2,
        "fengyun-shou"          : 2,
        "sanhua-zhang"          : 3,
        "shenzhang-bada"        : 3,
        "qianye-shou"           : 3,
        "xumishan-zhang"        : 4,
        "xiuluo-dao"            : 3,
        "wuchang-zhang"         : 3,
        "zui-gun"               : 3,
        "wuxiang-zhi"           : 4,
        "jingang-quan"          : 4,
        "fumo-jian"             : 4,
        "wuxiang-zhi"           : 3,
        "xiuluo-zhi"            : 5,
        "yingzhua-gong"         : 5,
        "nianhua-zhi"           : 5,
        "banruo-zhang"          : 4,
        "jingang-zhi"           : 7,
        "duoluoye-zhi"          : 6,
        "yizhi-chan"            : 7,
        "longzhua-gong"         : 8,
        "damo-jian"             : 5,
        "riyue-bian"            : 5,
        "taiji-jian"            : 4,
        "taiji-quan"            : 4,
        "xuanxu-dao"            : 3,
        "raozhi-roujian"        : 3,
        "shenmen-jian"          : 4,
        "yitian-zhang"          : 5,
        "huzhua-shou"           : 6,
        "zhenshan-zhang"        : 4,
        "dugu-jiujian"          : 6,
        "poyu-quan"             : 5,
        "hunyuan-zhang"         : 6,
        "fanliangyi-dao"        : 4,
        "kuangfeng-jian"        : 6,
        "yunv-sword"            : 4,
        "huashan-jianfa"        : 5,
        "huifeng-jian"          : 6,
        "piaoxue-zhang"         : 7,
        "yanxing-dao"           : 4,
        "tiangang-zhi"          : 6,
        "jinding-zhang"         : 4,
        "xiantian-gong"         : 6,
        "kongming-quan"         : 7,
        "chongyang-shenzhang"   : 3,
        "zhongnan-zhi"          : 4,
        "haotian-zhang"         : 4,
        "quanzhen-jian"         : 5,
        "tanzhi-shentong"       : 4,
        "yuxiao-jian"           : 5,
        "canglang-bian"         : 6,
        "lanhua-shou"           : 5,
        "xuanfeng-tui"          : 5,
        "luoying-shenjian"      : 4,
        "luoying-shenzhang"     : 5,
        "dragon-strike"         : 9,
        "dagou-bang"            : 4,
        "liuhe-dao"             : 3,
        "xiaoyaoyou"            : 5,
        "fengmo-zhang"          : 4,
        "shexing-diaoshou"      : 4,
        "fumo-zhang"            : 5,
        "suohou-gong"           : 8,
        "chansi-shou"           : 4,
        "jueming-tui"           : 6,
        "mantianhuayu"          : 3,
        "shenzhaojing"          : 8,
        "xuedao-daofa"          : 6,
        "liancheng-jianfa"      : 4,
        "mingwang-jian"         : 4,
        "yujiamu-quan"          : 5,
        "dashou-yin"            : 4,
        "longxiang-gong"        : 8,
        "riyue-lun"             : 5,
        "huoyan-dao"            : 6,
        "jingang-chu"           : 5,
        "chousui-zhang"         : 8,
        "sanyin-zhua"           : 6,
        "chanhun-suo"           : 4,
        "feixing-shu"           : 5,
        "tianshan-zhang"        : 5,
        "sad-strike"            : 8,
        "xuantie-jian"          : 6,
        "yunv-jian"             : 4,
        "chilian-shenzhang"     : 6,
        "yinsuo-jinling"        : 7,
        "tianluo-diwang"        : 5,
        "meinv-quan"            : 4,
        "yufeng-zhen"           : 3,
        "zhemei-shou"           : 5,
        "liuyue-jian"           : 5,
        "ruyi-dao"              : 4,
        "qingyun-shou"          : 4,
        "liuyang-zhang"         : 8,
        "youming-guizhao"       : 6,
        "zhougong-jian"         : 4,
        "wuliang-jian"          : 4,
        "tianyu-qijian"         : 5,
        "jiuyang-shengong"      : 7,
        "shenghuo-ling"         : 5,
        "hanbing-mianzhang"     : 5,
        "pili-shou"             : 6,
        "qishang-quan"          : 7,
        "duoming-jinhua"        : 4,
        "yingzhua-shou"         : 6,
        "liehuo-jian"           : 4,
        "huagu-mianzhang"       : 7,
        "shedao-qigong"         : 5,
        "hujia-daofa"           : 6,
        "baisheng-daofa"        : 6,
        "miaojia-jian"          : 5,
        "mantian-xing"          : 4,
        "tianchang-zhang"       : 4,
        "hujia-quan"            : 4,
        "hamagong"              : 6,
        "lingshe-quan"          : 4,
        "baibian-daxue"         : 4,
        "lingshe-zhangfa"       : 5,
        "shentuo-zhang"         : 5,
        "canhe-zhi"             : 5,
        "longcheng-shendao"     : 5,
        "murong-daofa"          : 4,
        "murong-jianfa"         : 5,
        "xingyi-zhang"          : 3,
        "qixing-quan"           : 4,
        "six-finger"            : 8,
        "yiyang-zhi"            : 6,
        "duanjia-jian"          : 5,
        "feifeng-bian"          : 4,
        "jinyu-quan"            : 5,
        "qiantian-zhi"          : 5,
        "wuluo-zhang"           : 4,
        "tangmen-throwing"      : 8,
        "wuzhan-mei"            : 5,
        "boyun-suowu"           : 5,
]);

int ap_power(object me, string skill)
{
        int lv, ap_power;
        string attack_skill;
              
        if (! stringp(attack_skill = me->query_skill_mapped(skill)))
        {
                ap_power = me->query_skill(skill) +
                           me->query("level") * COU + 
                           me->query_skill("martial-cognize", 1);
                return ap_power;
        }
        
        if (undefinedp(lv = attack_lvl[attack_skill]))        
                lv = 1;    
                    
        ap_power = me->query_skill(skill, 1) / 2 + 
                   me->query_skill(attack_skill, 1) * lv / BAS +
                   me->query("level") * COU + 
                   me->query_skill("martial-cognize", 1);
                   
        return ap_power;
}

int dp_power(object target, string skill)
{
        int lv, dp_power;
        string defend_skill;
         
        defend_skill = target->query_skill_mapped(skill); 
        
        if (! stringp(defend_skill = target->query_skill_mapped(skill)))
        {
                dp_power = target->query_skill(skill) +
                           target->query("level") * COU + 
                           target->query_skill("martial-cognize", 1);
                return dp_power;
        }
        
        if (skill == "parry")
        {        
                if (undefinedp(lv = parry_lvl[defend_skill]))        
                        lv = 1;   
        } else
        if (skill == "dodge")
        {
                if (undefinedp(lv = dodge_lvl[defend_skill]))        
                        lv = 1;                   
        } else
        if (skill == "force")
        {
                if (undefinedp(lv = force_lvl[defend_skill]))        
                        lv = 1;   
        } else
        {
                if (undefinedp(lv = defend_lvl[defend_skill]))       
                        lv = 1;
        }                    
                    
        dp_power = target->query_skill(skill, 1) / 2 + 
                   target->query_skill(defend_skill, 1) * lv / BAS +
                   target->query("level") * COU + 
                   target->query_skill("martial-cognize", 1);
                   
        return dp_power;
}


int da_power(object me, string skill)
{
        int lv, da_power;
        string attack_skill;
        
              
        if (! stringp(attack_skill = me->query_skill_mapped(skill)))
        {
                da_power = me->query_skill(skill) +
                           me->query("level") * COU + 
                           me->query_skill("martial-cognize", 1);
                
                da_power = da_power / 2 + random(da_power);
                da_power /= 5;
                return da_power;
        }
        
        if (undefinedp(lv = damage_lvl[attack_skill]))        
                lv = 1;    
                    
        da_power = me->query_skill(skill, 1) / 2 + 
                   me->query_skill(attack_skill, 1) * lv / BAS +
                   me->query("level") * COU + 
                   me->query_skill("martial-cognize", 1);
                          
        da_power = da_power / 2 + random(da_power);
        da_power /= 5;                   
        return da_power;
}                        
