// Code of ShenZhou
// 【神州】现在有以下大区域

mapping region_names = ([
	"baituo"   : "西域白驼山",
	"beijing"  : "北京",
	"changan"  : "长安",
	"city"     : "扬州",
	"city3"    : "成都",
	"dali"     : "云南大理",
	"death"    : "鬼门关",
	"emei"     : "四川峨嵋",
	"foshan"   : "广东佛山",
	"fuzhou"   : "福建福州",
	"gaibang"  : "丐帮所在地",
	"guanwai"  : "关外",
	"guiyun"   : "归云庄",
	"gumu"     : "古墓派",
	"hangzhou" : "杭州",
	"heimuya"  : "黑木崖",
	"hengshan" : "恒山",
	"henshan"  : "衡山",
	"huanggon" : "皇宫",
	"huanghe"  : "黄河边",
	"huashan"  : "华山",
	"jinshe"   : "华山金蛇洞",
	"lingjiu"  : "灵鹫宫",
	"lingzhou" : "灵州",
	"meizhuang": "梅庄",
	"mingjiao" : "明教",
	"pk"	    : "屠人场",
	"qingcheng": "青城山",
	"quanzhen" : "全真派",
	"shaolin"  : "少林寺",
	"shenlong" : "神龙岛",
	"songshan" : "嵩山",
	"suzhou"   : "苏州",
	"taishan"  : "泰山",
	"taohua"   : "桃花岛",
	"tianlongsi": "天龙寺",
	"tulong"   : "万安寺或者王盘山岛",
	"village"  : "华山村",
	"wanjiegu" : "万劫谷",
	"wizard"   : "仙界",
	"wudang"   : "武当山",
	"xiakedao" : "侠客岛",
	"xiangyang": "襄阳",
	"xiaoyao"  : "逍遥派",
	"xingxiu"  : "星宿派",
	"xuedao"   : "血刀门",
	"xueshan"  : "雪山寺",
	"yangziwu" : "燕子钨",
]);
