#include <ansi.h>

mapping *quest = ({
	([
		"id":          "shutong gun",
		"name":        "ÊìÍ­¹÷",
		"type":        "Ñ°",
		"bonus":       101,
		"msg1":        "",
		"object":      "/d/heimuya/npc/obj/shutonggun.c",
	]),
	([
		"id":          "cloth",
		"name":        "µ­»ÆÉÀ",
		"type":        "Ñ°",
		"bonus":       101,
		"msg1":        "",
		"object":      "/d/emei/obj/ycloth.c",
	]),
	([
		"id":          "leizhen dang",
		"name":        "À×Õðµ²",
		"type":        "Ñ°",
		"bonus":       101,
		"msg1":        "",
		"object":      "/d/heimuya/npc/obj/leizhendang.c",
	]),
	([
		"id":          "xuan tie",
		"name":        "[36mÐþÌúÊ¯[2;37;0m",
		"type":        "Ñ°",
		"bonus":       61,
		"msg1":        "",
		"object":      "/d/item/obj/xuantie.c",
	]),
	([
		"id":          "cloth",
		"name":        "ÊìÂÞ³¤ÅÛ",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/henshan/npc/obj/luo_cloth.c",
	]),
	([
		"id":          "da fu",
		"name":        "´ó¸«",
		"type":        "Ñ°",
		"bonus":       101,
		"msg1":        "",
		"object":      "/d/heimuya/npc/obj/dafu.c",
	]),
	([
		"id":          "cloth",
		"name":        "°×²¼³¤ÅÛ",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/mingjiao/obj/baipao.c",
	]),
	([
		"id":          "muyu",
		"name":        "Ä¾Óã´¸",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/wanjiegu/npc/obj/muyu.c",
	]),
	([
		"id":          "jiasha",
		"name":        "[30mºÚÉ«ôÂôÄ[2;37;0m",
		"type":        "Ñ°",
		"bonus":       86,
		"msg1":        "",
		"object":      "/d/xueshan/obj/b-jiasha.c",
	]),
	([
		"id":          "bosi cloth",
		"name":        "[35m²¨Ë¹Ã÷½Ì½Ì·þ[2;37;0m",
		"type":        "Ñ°",
		"bonus":       84,
		"msg1":        "",
		"object":      "/d/tulong/yitian/npc/obj/jiaofu.c",
	]),
	([
		"id":          "duanchang hua",
		"name":        "[1;31m¶Ï³¦»¨[2;37;0m",
		"type":        "Ñ°",
		"bonus":       90,
		"msg1":        "",
		"object":      "/d/shenlong/obj/hua3.c",
	]),
	([
		"id":          "jia sha",
		"name":        "»¤·¨ôÂôÄ",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/shaolin/obj/xuan-cloth.c",
	]),
	([
		"id":          "cloth",
		"name":        "[1;33mÒ»Æ·ÊÌÎÀ×°[2;37;0m",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/beijing/npc/obj/guanfu2.c",
	]),
	([
		"id":          "huang magua",
		"name":        "[1;33m»ÆÂí¹Ó[2;37;0m",
		"type":        "Ñ°",
		"bonus":       72,
		"msg1":        "",
		"object":      "/d/beijing/npc/obj/goldcloth1.c",
	]),
	([
		"id":          "cloth",
		"name":        "[1;34mÇà²¼³¤ÉÀ[2;37;0m",
		"type":        "Ñ°",
		"bonus":       95,
		"msg1":        "",
		"object":      "/d/beijing/npc/obj/cloth1.c",
	]),
});
mapping query_questsn()
{
        return quest[random(sizeof(quest))];
}
